/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.bonbons.demo.models.entities;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.*;


@Getter
@Setter
@NoArgsConstructor

public class Commentaire {

    private long id;


    private String texte;

    private Date dateCommentaire;

    private Produit produit;


    private Utilisateur utilisateur;


}