/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.bonbons.demo.models.entities;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.*;


@Getter
@Setter
@NoArgsConstructor

public class Inventaire {

    private long id;


    private int quantite;


    private float prix;


    private String portion;


    private Produit inventaires;


    private List<Commande> commandes = new ArrayList<Commande>();


}