/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.bonbons.demo.models.entities;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGAQXvR1U2J1NY= >>
// ----------- >>

@Getter
@Setter
@NoArgsConstructor

public class Note {

    private int note;


}