/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.bonbons.demo.models.entities;

import com.bonbons.demo.models.entities.Categorie;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;


@Getter
@Setter
@NoArgsConstructor

@Entity
public class Produit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;


    private String nom;


    private String image;


   // private List<Inventaire> inventaires = new ArrayList<Inventaire>();


    @ManyToOne
    private Categorie categorie;


    //private List<Commentaire> commentaires = new ArrayList<Commentaire>();

   // private Utilisateur notes;


}