/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.bonbons.demo.models.entities;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.*;



@Entity
@Getter
@Setter
@NoArgsConstructor

public class Utilisateur {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    private String nom;

    private String prenom;


    private String email;


    private String mdp;

//    private List<Commande> utilisateurs = new ArrayList<Commande>();


    @ManyToOne
    private Role role;

//    private List<Commentaire> commentaires = new ArrayList<Commentaire>();
//
//
//    private List<Produit> notes = new ArrayList<Produit>();


}